core/cart/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cart'


urlpatterns = [
    path("session/add-product/",views.SessionAddProductView.as_view(),name="session-add-product"),
    path("session/remove-product/",views.SessionRemoveProductView.as_view(),name="session-remove-product"),
    path("session/update-product-quantity/",views.SessionUpdateProductQuantityView.as_view(),name="session-update-product-quantity"),
    path("summary/",views.CartSummaryView.as_view(),name="cart-summary")
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('review/', include('review.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),
                    ]

core/website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("submit/ticket/", views.SendContactView.as_view(), name="submit-ticket"),
    path("newsletter/", views.NewsletterView.as_view(), name="newsletter"),
]

core/website/models.py
from django.db import models
from django.contrib.auth import get_user_model


# fetching user model
User = get_user_model()

# defining the status of items to be saved or released
class ContactModel(models.Model):

    full_name = models.CharField(max_length=200)
    email = models.EmailField(default=None, null=True)
    phone_number = models.CharField(max_length=200, blank=True, null=True)
    subject = models.CharField(max_length=200, blank=True, null=True)
    content = models.TextField(max_length=700)
    is_seen = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.full_name


class NewsLetter(models.Model):
    email = models.EmailField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email

core/website/forms.py
from typing import Any
from django import forms
from .models import ContactModel,NewsLetter


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        fields = ["subject","full_name","email","phone_number","content"]
        
        error_messages = {
            'email': {
                'required': "فیلد ایمیل نمی تواند خالی باشد"
            },
            'content': {
                'required': "فیلد محتوا نمی تواند خالی باشد",
                'min_length': "طول محتوای وارد شده غیر مجاز است"
            },
            'subject': {
                'required': "فیلد  عنوان نمی تواند خالی باشد"
            },
            'full_name': {
                'required': "فیلد نام و نام خانوادگی نمی تواند خالی باشد"
            }
        }
    

class NewsLetterForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100, required=False)
    class Meta:
        model = NewsLetter
        fields = ['email',"first_name"]

    def clean_first_name(self):
        if len(self.cleaned_data['first_name']) > 0:
            raise forms.ValidationError("Please leave this field blank.")
        return self.cleaned_data['first_name']
    
    def save(self, commit=True):
        newsletter, created = NewsLetter.objects.get_or_create(email=self.cleaned_data.get("email"))
        return newsletter

core/dashboard/admin/views/contacts.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import (
    ListView,
    DetailView,

)


from website.models import NewsLetter,ContactModel
from django.contrib.auth.mixins import LoginRequiredMixin
from dashboard.permissions import *
from django.db.models import F,Q
from django.core import exceptions


class ContactListView(LoginRequiredMixin,HasAdminAccessPermission, ListView):
    title = "لیست تماس ها"
    template_name = "dashboard/admin/contacts/contact-list.html"
    paginate_by = 10
    ordering = "-created_date"

    def get_paginate_by(self, queryset):
        """
        Paginate by specified value in querystring, or use default class property value.
        """
        return self.request.GET.get('paginate_by', self.paginate_by)

    def get_queryset(self):
        queryset = ContactModel.objects.all().order_by("-created_date")
        search_query = self.request.GET.get('q', None)
        ordering_query = self.request.GET.get('ordering', None)

        if search_query:
            queryset = queryset.filter(
                 Q(email__icontains=search_query) |
                 Q(subject__icontains=search_query) |
                 Q(content__icontains=search_query) |
                 Q(phone_number__icontains=search_query)
            )
        if ordering_query:
            try:
                queryset = queryset.order_by(ordering_query)
            except exceptions.FieldError:
                pass
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total_result"] = self.get_queryset().count()
        return context



class ContactDetailView(LoginRequiredMixin,HasAdminAccessPermission, DetailView):
    title = "جزئیات تماس"
    template_name = "dashboard/admin/contacts/contact-detail.html"
    
    def get_object(self, queryset=None ):
        contact_obj = get_object_or_404(ContactModel,pk=self.kwargs.get("pk"))
        if not contact_obj.is_seen:
            contact_obj.is_seen = True
            contact_obj.save()
        return contact_obj

core/website/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import *
from .forms import ContactForm, NewsLetterForm
from django.contrib import messages
from django.views.generic import CreateView
from django.shortcuts import redirect
# Create your views here.


class IndexView(TemplateView):
    template_name = "website/index.html"

class ContactView(TemplateView):
    template_name = "website/contact.html"

class AboutView(TemplateView):
    template_name = "website/about.html"

class SendContactView(CreateView):
    """
    a class based view to show index page
    """
    http_method_names = ['post']
    form_class = ContactForm

    def form_valid(self, form):
        form.save()
        messages.success(
            self.request, 'تیکت شما با موفقیت ثبت شد و در اسرع وقت با شما تماس حاصل خواهد شد')
        return super().form_valid(form)

    def form_invalid(self, form):
        # handle unsuccessful form submission
        messages.error(
            self.request, 'مشکلی در ارسال فرم شما پیش آمد لطفا ورودی ها رو بررسی کنین و مجدد ارسال نمایید')
        return redirect(self.request.META.get('HTTP_REFERER'))

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')
    
class NewsletterView(CreateView):
    http_method_names = ['post']
    form_class = NewsLetterForm
    success_url = '/'

    def form_valid(self, form):
        # handle successful form submission
        messages.success(
            self.request, 'از ثبت نام شما ممنونم، اخبار جدید رو براتون ارسال می کنم 😊👍')
        return super().form_valid(form)

    def form_invalid(self, form):
        # handle unsuccessful form submission
        messages.error(
            self.request, 'مشکلی در ارسال فرم شما وجود داشت که می دونم برا چی بود!! چون ربات هستید!')
        return redirect('website:index')

core/templates/website/contact.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Hero -->
<div class="position-relative bg-img-start" style="background-image: url({%static 'svg/components/card-11.svg' %});">
    <div class="container content-space-t-3 content-space-t-lg-5 content-space-b-2 position-relative zi-2">
        <div class="w-md-75 w-lg-50 text-center mx-md-auto mb-5 mb-md-9">
            <h1>تماس با ما</h1>
            <p>نظرات و انتقادات خود را بیان کنین</p>
        </div>

        <div class="row">
            <div class="col-md-4 mb-3 mb-md-0">
                <!-- Card -->
                <a class="card card-transition text-center h-100" href="#">
                    <div class="card-body">
                        <div class="svg-icon text-primary mb-3">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path opacity="0.3" fill-rule="evenodd" clip-rule="evenodd"
                                    d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z"
                                    fill="#035A4B"></path>
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                    d="M10.591 13.209V14.868H11.851C14.392 14.868 16.387 12.915 16.387 10.395C16.387 7.875 14.392 5.922 11.851 5.922C9.31 5.922 7.336 7.875 7.336 10.395H9.121C9.121 8.799 10.234 7.581 11.851 7.581C13.447 7.581 14.602 8.799 14.602 10.395C14.602 11.991 13.447 13.209 11.851 13.209H10.591ZM12 16C11.4477 16 11 16.4477 11 17C11 17.5523 11.4477 18 12 18C12.5523 18 13 17.5523 13 17C13 16.4477 12.5523 16 12 16Z"
                                    fill="#035A4B"></path>
                            </svg>

                        </div>

                        <h4 class="card-title">مشاوره خرید</h4>
                        <p class="card-text text-body">دانش کافی در زمان خرید داشته باشید</p>
                    </div>

                    <div class="card-footer pt-0">
                        <span class="card-link">تماس با پشتیبانی <i class="bi-chevron-left small ms-1"></i></span>
                    </div>
                </a>
                <!-- End Card -->
            </div>
            <!-- End Col -->

            <div class="col-md-4 mb-3 mb-md-0">
                <!-- Card -->
                <a class="card card-transition text-center h-100" href="#">
                    <div class="card-body">
                        <div class="svg-icon text-primary mb-3">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                    d="M22.1671 18.1421C22.4827 18.4577 23.0222 18.2331 23.0206 17.7868L23.0039 13.1053V5.52632C23.0039 4.13107 21.8729 3 20.4776 3H8.68815C7.2929 3 6.16183 4.13107 6.16183 5.52632V9H13C14.6568 9 16 10.3431 16 12V15.6316H19.6565L22.1671 18.1421Z"
                                    fill="#035A4B"></path>
                                <path opacity="0.3" fill-rule="evenodd" clip-rule="evenodd"
                                    d="M1.98508 18V13C1.98508 11.8954 2.88051 11 3.98508 11H11.9851C13.0896 11 13.9851 11.8954 13.9851 13V18C13.9851 19.1046 13.0896 20 11.9851 20H4.10081L2.85695 21.1905C2.53895 21.4949 2.01123 21.2695 2.01123 20.8293V18.3243C1.99402 18.2187 1.98508 18.1104 1.98508 18ZM5.99999 14.5C5.99999 14.2239 6.22385 14 6.49999 14H11.5C11.7761 14 12 14.2239 12 14.5C12 14.7761 11.7761 15 11.5 15H6.49999C6.22385 15 5.99999 14.7761 5.99999 14.5ZM9.49999 16C9.22385 16 8.99999 16.2239 8.99999 16.5C8.99999 16.7761 9.22385 17 9.49999 17H11.5C11.7761 17 12 16.7761 12 16.5C12 16.2239 11.7761 16 11.5 16H9.49999Z"
                                    fill="#035A4B"></path>
                            </svg>

                        </div>

                        <h4 class="card-title">سوالات متداول</h4>
                        <p class="card-text text-body">سوالات خود را از ما بپرسید و پیدا کنین</p>
                    </div>

                    <div class="card-footer pt-0">
                        <span class="card-link">مشاهده سوالات<i class="bi-chevron-left small ms-1"></i></span>
                    </div>
                </a>
                <!-- End Card -->
            </div>
            <!-- End Col -->

            <div class="col-md-4">
                <!-- Card -->
                <a class="card card-transition text-center h-100" href="#">
                    <div class="card-body">
                        <div class="svg-icon text-primary mb-3">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path opacity="0.3"
                                    d="M19.0687 17.9688H11.0687C10.4687 17.9688 10.0687 18.3687 10.0687 18.9688V19.9688C10.0687 20.5688 10.4687 20.9688 11.0687 20.9688H19.0687C19.6687 20.9688 20.0687 20.5688 20.0687 19.9688V18.9688C20.0687 18.3687 19.6687 17.9688 19.0687 17.9688Z"
                                    fill="#035A4B"></path>
                                <path
                                    d="M4.06875 17.9688C3.86875 17.9688 3.66874 17.8688 3.46874 17.7688C2.96874 17.4688 2.86875 16.8688 3.16875 16.3688L6.76874 10.9688L3.16875 5.56876C2.86875 5.06876 2.96874 4.46873 3.46874 4.16873C3.96874 3.86873 4.56875 3.96878 4.86875 4.46878L8.86875 10.4688C9.06875 10.7688 9.06875 11.2688 8.86875 11.5688L4.86875 17.5688C4.66875 17.7688 4.36875 17.9688 4.06875 17.9688Z"
                                    fill="#035A4B"></path>
                            </svg>

                        </div>

                        <h4 class="card-title">کمک به توسعه</h4>
                        <p class="card-text text-body">پیشنهادات سازنده خود را به توسعه دهندگان انتقال دهید</p>
                    </div>

                    <div class="card-footer pt-0">
                        <span class="card-link">تماس با پشتیبانی<i class="bi-chevron-left small ms-1"></i></span>
                    </div>
                </a>
                <!-- End Card -->
            </div>
            <!-- End Col -->
        </div>
        <!-- End Row -->
    </div>

    <!-- Shape -->
    <div class="shape shape-bottom zi-1">
        <svg width="3000" height="500" viewBox="0 0 3000 500" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 500H3000V0L0 500Z" fill="#fff"></path>
        </svg>
    </div>
    <!-- End Shape -->
</div>
<!-- End Hero -->

<!-- Contact Form -->
<div class="container content-space-1 content-space-lg-1">
    <div class="mx-auto" style="max-width: 35rem;">
        <!-- Card -->
        <div class="card">
            <div class="card-body">
                <!-- Heading -->
                <div class="text-center mb-5 mb-md-9">
                    <h2>فرم تماس با پشتیبانی</h2>
                    <p>سوال یا نظرات خود را مطرح کنین</p>
                </div>
                <!-- End Heading -->

                <!-- Form -->
                <form action="{% url 'website:submit-ticket' %}" method="post">
                    {% csrf_token %}
                    <div class="row gx-3">
                        <div class="col-sm-12">
                            <!-- Form -->
                            <div class="mb-3">
                                <label class="form-label" for="formFirstName">نام و نام خانوادگی</label>
                                <input type="text" class="form-control form-control-lg" name="full_name"
                                    id="formFirstName" placeholder="نام و نام خانوادگی" required>
                            </div>
                            <!-- End Form -->
                        </div>
                        <!-- End Col -->

                   
                    </div>
                    <!-- End Row -->

                    <div class="row gx-3">
                        <div class="col-sm-6">
                            <!-- Form -->
                            <div class="mb-3">
                                <label class="form-label" for="formEmail">آدرس ایمیل</label>
                                <input type="email" class="form-control form-control-lg " name="email" dir="ltr"
                                    id="formEmail" placeholder="email@site.com" aria-label="email@site.com" required>
                            </div>
                            <!-- End Form -->
                        </div>
                        <!-- End Col -->

                        <div class="col-sm-6">
                            <!-- Form -->
                            <div class="mb-3">
                                <label class="form-label" for="formPhoneNumber">شماره همراه </label>
                                <input type="text" class="form-control form-control-lg " name="phone_number" dir="ltr"
                                    id="formPhoneNumber" placeholder="+9891200000" required>
                            </div>
                            <!-- End Form -->
                        </div>
                        <!-- End Col -->
                    </div>
                    <!-- End Row -->
                    <div class="row gx-3">
                        <div class="col-sm-12">
                            <!-- Form -->
                            <div class="mb-3">
                                <label class="form-label" for="formSubject">موضوع</label>
                                <input type="text" class="form-control form-control-lg" name="subject"
                                    id="formSubject" placeholder="موضوع مورد نظر را وارد نمایید" aria-label="First name" required>
                            </div>
                            <!-- End Form -->
                        </div>
                        <!-- End Col -->

                   
                    </div>
                    <!-- Form -->
                    <div class="mb-3">
                        <label class="form-label" for="formDescription">توضیحات</label>
                        <textarea class="form-control form-control-lg" name="content"
                            id="formDescription" placeholder="توضیحات خود را وارد نمایید"
                            aria-label="Tell us about your ..." rows="4" required></textarea>
                    </div>
                    <!-- End Form -->

                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary btn-lg">ارسال درخواست</button>
                    </div>

                    <div class="text-center">
                        <p class="form-text">تیکت ها در اسرع وقت پاسخ داده خواهند شد</p>
                    </div>
                </form>
                <!-- End Form -->
            </div>
        </div>
        <!-- End Card -->
    </div>
</div>
<!-- End Contact Form -->


{% endblock content %}