core/cart/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cart'


urlpatterns = [
    path("session/add-product/",views.SessionAddProductView.as_view(),name="session-add-product"),
    path("session/remove-product/",views.SessionRemoveProductView.as_view(),name="session-remove-product"),
    path("session/update-product-quantity/",views.SessionUpdateProductQuantityView.as_view(),name="session-update-product-quantity"),
    path("summary/",views.CartSummaryView.as_view(),name="cart-summary")
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('review/', include('review.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),
                    ]

core/shop/urls.py
from django.urls import path, re_path
from . import views

app_name = 'shop'

urlpatterns = [
    path("product/grid/", views.ShopProductGridView.as_view(), name="product-grid"),
    re_path(r"product/(?P<slug>[-\w]+)/detail/",views.ShopProductDetailView.as_view(),
    name="product-detail"),
    path("add-or-remove-wishlist/", views.AddOrRemoveWishlistView.as_view(), name="add-or-remove-wishlist"),

]

core/shop/models.py
from django.db import models
from decimal import Decimal
from django.core.validators import MaxValueValidator, MinValueValidator


class ProductStatusType(models.IntegerChoices):
    publish = 1 ,("نمایش")
    draft = 2 ,("عدم نمایش")


class ProductCategoryModel(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True,unique=True)    
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ["-created_date"]
        
    def __str__(self):
        return self.title


# Create your models here.
class ProductModel(models.Model):
    user = models.ForeignKey("accounts.User",on_delete=models.PROTECT)
    category = models.ManyToManyField(ProductCategoryModel)
    title = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True,unique=True)
    image = models.ImageField(default="/default/product-image.png",upload_to="product/img/")
    description = models.TextField()
    brief_description = models.TextField(null=True,blank=True)
    
    stock = models.PositiveIntegerField(default=0)
    status = models.IntegerField(choices=ProductStatusType.choices,default=ProductStatusType.draft.value)
    price = models.DecimalField(default=0,max_digits=10,decimal_places=0)
    discount_percent = models.IntegerField(default=0,validators = [MinValueValidator(0),MaxValueValidator(100)])
    
    avg_rate = models.FloatField(default=0.0)
    
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ["-created_date"]
        
    def __str__(self):
        return self.title
    
    def get_price(self):        
        discount_amount = self.price * Decimal(self.discount_percent / 100)
        discounted_amount = self.price - discount_amount
        return round(discounted_amount)
    
    def is_discounted(self):
        return self.discount_percent != 0
    
    def is_published(self):
        return self.status == ProductStatusType.publish.value
    
class ProductImageModel(models.Model):
    product = models.ForeignKey(ProductModel,on_delete=models.CASCADE,related_name="product_images")
    file = models.ImageField(upload_to="product/extra-img/")
    
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ["-created_date"]
        
class WishlistProductModel(models.Model):
    user = models.ForeignKey("accounts.User",on_delete=models.PROTECT)
    product = models.ForeignKey(ProductModel,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.product.title

core/dashboard/admin/forms/products.py
from django import forms
from shop.models import ProductModel,ProductImageModel
class ProductForm(forms.ModelForm):


    class Meta:
        model = ProductModel
        fields = [
            "category",
            "title",
            "slug",
            "image",
            "description",
            "brief_description",
            "stock",
            "status",
            "price",
            "discount_percent",
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['slug'].widget.attrs['class'] = 'form-control'
        self.fields['category'].widget.attrs['class'] = 'form-control'
        self.fields['image'].widget.attrs['class'] = 'form-control'
        self.fields['brief_description'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['id'] = 'ckeditor'
        self.fields['stock'].widget.attrs['class'] = 'form-control'
        self.fields['stock'].widget.attrs['type'] = 'number'
        self.fields['status'].widget.attrs['class'] = 'form-select'
        self.fields['price'].widget.attrs['class'] = 'form-control'
        self.fields['discount_percent'].widget.attrs['class'] = 'form-control'


class ProductImageForm(forms.ModelForm):


    class Meta:
        model = ProductImageModel
        fields = [
            "file",
        ]
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['file'].widget.attrs['class'] = 'form-control'
        self.fields['file'].widget.attrs['accept'] = 'image/png, image/jpg, image/jpeg'

core/dashboard/admin/views/products.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.forms.forms import BaseForm
from django.http.response import HttpResponse
from django.views.generic import (
    View,
    TemplateView,
    UpdateView,
    ListView,
    DeleteView,
    CreateView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from dashboard.permissions import HasAdminAccessPermission
from django.contrib.auth import views as auth_views
from dashboard.admin.forms import *
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from accounts.models import Profile
from django.shortcuts import redirect
from django.contrib import messages
from shop.models import ProductModel, ProductCategoryModel, ProductStatusType
from django.core.exceptions import FieldError


class AdminProductListView(LoginRequiredMixin, HasAdminAccessPermission, ListView):
    template_name = "dashboard/admin/products/product-list.html"
    paginate_by = 10

    def get_paginate_by(self, queryset):
        return self.request.GET.get('page_size', self.paginate_by)

    def get_queryset(self):
        queryset = ProductModel.objects.all()
        if search_q := self.request.GET.get("q"):
            queryset = queryset.filter(title__icontains=search_q)
        if category_id := self.request.GET.get("category_id"):
            queryset = queryset.filter(category__id=category_id)
        if min_price := self.request.GET.get("min_price"):
            queryset = queryset.filter(price__gte=min_price)
        if max_price := self.request.GET.get("max_price"):
            queryset = queryset.filter(price__lte=max_price)
        if order_by := self.request.GET.get("order_by"):
            try:
                queryset = queryset.order_by(order_by)
            except FieldError:
                pass
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total_items"] = self.get_queryset().count()
        context["categories"] = ProductCategoryModel.objects.all()
        return context


class AdminProductCreateView(LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, CreateView):
    template_name = "dashboard/admin/products/product-create.html"
    queryset = ProductModel.objects.all()
    form_class = ProductForm
    success_message = "ایجاد محصول با موفقیت انجام شد"

    def form_valid(self, form):
        form.instance.user = self.request.user
        super().form_valid(form)
        return redirect(reverse_lazy("dashboard:admin:product-edit", kwargs={"pk": form.instance.pk}))

    def get_success_url(self):
        return reverse_lazy("dashboard:admin:product-list")


class AdminProductEditView(LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, UpdateView):
    template_name = "dashboard/admin/products/product-edit.html"
    queryset = ProductModel.objects.all()
    form_class = ProductForm
    success_message = "ویرایش محصول با موفقیت انجام شد"

    def get_success_url(self):
        return reverse_lazy("dashboard:admin:product-edit", kwargs={"pk": self.get_object().pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["image_form"] = ProductImageForm()
        return context

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.product_images.prefetch_related()
        return obj


class AdminProductDeleteView(LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, DeleteView):
    template_name = "dashboard/admin/products/product-delete.html"
    queryset = ProductModel.objects.all()
    success_url = reverse_lazy("dashboard:admin:product-list")
    success_message = "حذف محصول با موفقیت انجام شد"


class AdminProductAddImageView(LoginRequiredMixin, HasAdminAccessPermission, CreateView):
    http_method_names = ['post']
    form_class = ProductImageForm

    def get_success_url(self):
        return reverse_lazy('dashboard:admin:product-edit', kwargs={'pk': self.kwargs.get('pk')})

    def get_queryset(self):
        return ProductImageModel.objects.filter(product__id=self.kwargs.get('pk'))

    def form_valid(self, form):
        form.instance.product = ProductModel.objects.get(
            pk=self.kwargs.get('pk'))
        # handle successful form submission
        messages.success(
            self.request, 'تصویر مورد نظر با موفقیت ثبت شد')
        return super().form_valid(form)

    def form_invalid(self, form):
        # handle unsuccessful form submission
        messages.error(
            self.request, 'اشکالی در ارسال تصویر رخ داد لطفا مجدد امتحان نمایید')
        return redirect(reverse_lazy('dashboard:admin:product-edit', kwargs={'pk': self.kwargs.get('pk')}))


class AdminProductRemoveImageView(LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, DeleteView):
    http_method_names = ["post"]
    success_message = "تصویر مورد نظر با موفقیت حذف شد"

    def get_queryset(self):
        return ProductImageModel.objects.filter(product__id=self.kwargs.get('pk'))
    
    def get_object(self, queryset=None):
        return self.get_queryset().get(pk=self.kwargs.get('image_id'))

    def get_success_url(self):
        return reverse_lazy('dashboard:admin:product-edit', kwargs={'pk': self.kwargs.get('pk')})

    def form_invalid(self, form):
        messages.error(
            self.request, 'اشکالی در حذف تصویر رخ داد لطفا مجدد امتحان نمایید')
        return redirect(reverse_lazy('dashboard:admin:product-edit', kwargs={'pk': self.kwargs.get('pk')}))

core/templates/dashbord/admin/products/product-create.html
{% extends 'dashboard/admin/base.html' %}
{% load static %}


{% block extra_css %}
<style>
    .small-primary-button {
        padding: 3px 10px;
        background-color: #007bff; 
        color: white; 
        border: none; 
        cursor: pointer; 
        font-size: 10px;
        border-radius: 5px; 
    }
    
    .small-primary-button:hover,
    .small-primary-button:focus {
        background-color: #0056b3;
    }
</style>

{% endblock %}



{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-light mb-0">
        <li class="breadcrumb-item">حساب</li>
        <li class="breadcrumb-item">داشبورد ادمین</li>
        <li class="breadcrumb-item">محصولات</li>
        <li class="breadcrumb-item active" aria-current="page">
            ایجاد محصول
        </li>
    </ol>
</nav>
{% endblock %}

{% block content %}
<div class="card">
    <!-- Header -->
    <div class="card-header border-bottom">
        <h5 class="card-header-title">ایجاد محصول</h5>
    </div>
    <!-- End Header -->

    <!-- Body -->
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card-body">
            <div class="row d-flex ">
                <div class="col-md-6 mb-3">
                    <label>نام محصول</label>
                    {{form.title}}
                </div>
                <div class="col-md-6 mb-3">
                    <label>slug محصول - <button class="small-primary-button" type="button"
                        onclick="generateSlug()">ساخت slug</button> </label>
                    {{form.slug}}
                </div>
                <div class="col-md-6 mb-3">
                    <label>تعداد</label>
                    {{form.stock}}
                </div>

                <div class="col-md-6 mb-3">
                    <label>وضعیت</label>
                    {{form.status}}
                </div>
                <div class="col-md-6 mb-3">
                    <label>دسته بندی</label>
                    {{form.category}}
                </div>
                <div class="col-md-4 mb-3">
                    <label>قیمت</label>
                    {{form.price}}
                </div>
                <div class="col-md-2 mb-3">
                    <label>درصد تخفیف</label>
                    {{form.discount_percent}}
                </div>

                <div class="col-md-12 mb-3">
                    <label>توضیح کوتاه</label>
                    {{form.brief_description}}
                </div>
                <div class="col-md-12 mb-3">
                    <label>توضیحات</label>
                    {{form.description}}
                </div>

                <div class="col-md-12 mb-3">
                    <label for="validationValidFileInput1">تصویر محصول</label>
                    {{form.image}}
                </div>


            </div>
            <div class="card-footer">
                <div class=" d-flex pt-5 justify-content-end">
                    <a class="btn btn-secondary ms-3" href="{% url 'dashboard:admin:product-list' %}">بازگشت</a>
                    <button class="btn btn-primary ms-3" type="submit">ایجاد محصول</button>
                </div>
            </div>
    </form>
</div>

{% endblock %}

{% block extra_js %}
<script>

    function generateSlug() {
        const title = $("#id_title").val();
        const slug = slugify(title);
        $("#id_slug").val(slug)
    }

    function slugify(titleStr) {
        titleStr = titleStr.replace(/^\s+|\s+$/g, '');
        titleStr = titleStr.toLowerCase();
        //persian support
        titleStr = titleStr.replace(/[^a-z0-9_\s-ءاأإآؤئبتثجحخدذرزسشصضطظعغفقكلمنهويةى]#u/, '')
            // Collapse whitespace and replace by -
            .replace(/\s+/g, '-')
            // Collapse dashes
            .replace(/-+/g, '-');
        slugStr = titleStr;
        return slugStr;
    }
</script>
{% endblock %}

{% block extra_js_no_compress %}
<script src="{% static 'vendor/ckeditor/ckeditor.js' %}"></script>
<script>
    // Replace 'editor' with the id of your textarea
    CKEDITOR.replace('ckeditor');
</script>
{% endblock %}

core/templates/dashbord/admin/products/product-delete.html
{% extends 'dashboard/admin/base.html' %}
{% load static %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-light mb-0">
        <li class="breadcrumb-item">حساب</li>
        <li class="breadcrumb-item">داشبورد ادمین</li>
        <li class="breadcrumb-item">محصولات</li>
        <li class="breadcrumb-item active" aria-current="page">
            حذف محصول
        </li>
    </ol>
</nav>
{% endblock %}

{% block content %}
<div class="card">
    <!-- Header -->
    <div class="card-header border-bottom">
        <h5 class="card-header-title">حذف محصول</h5>
    </div>
    <!-- End Header -->

    <!-- Body -->
    <form action="." method="post">
        {% csrf_token %}
        <div class="card-body">
            <div class="row d-flex ">
                <p> آیا از حذف محصول زیر اطمینان دارید؟</p>
                <div class="row">
                     <span>شناسه محصول  : {{object.pk}}</span>
                     <span>نام محصول  : {{object.title}}</span>
                </div>

            </div>
            <div class="card-footer">
                <div class=" d-flex pt-5 justify-content-end">
                    <button type="submit" class="btn btn-danger ms-3">تایید حذف</button>
                    <a class="btn btn-secondary ms-3" href="{% url 'dashboard:admin:product-edit' pk=object.pk %}">بازگشت</a>
                </div>
            </div>
    </form>
</div>

{% endblock %}

core/templates/dashbord/admin/products/product-edit.html
{% extends 'dashboard/admin/base.html' %}
{% load static %}


{% block extra_css %}
<style>
    .small-primary-button {
        padding: 3px 10px;
        background-color: #007bff;
        color: white;
        border: none;
        cursor: pointer;
        font-size: 10px;
        border-radius: 5px;
    }

    .small-primary-button:hover,
    .small-primary-button:focus {
        background-color: #0056b3;
    }
</style>
{% endblock %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-light mb-0">
        <li class="breadcrumb-item">حساب</li>
        <li class="breadcrumb-item">داشبورد ادمین</li>
        <li class="breadcrumb-item">محصولات</li>
        <li class="breadcrumb-item active" aria-current="page">
            ویرایش محصول
        </li>
    </ol>
</nav>
{% endblock %}

{% block content %}
<div class="row">
    <div>
        <div class="card mb-5">
            <!-- Header -->
            <div class="card-header border-bottom d-flex justify-content-between align-items-center">
                <h5 class="card-header-title">ویرایش محصول</h5>
                {% if object.is_published %}
                <a class="btn btn-sm btn-primary" target="_blank"
                    href="{% url 'shop:product-detail' slug=object.slug %}">نمایش
                    محصول</a>
                {% endif %}
            </div>
            <!-- End Header -->

            <!-- Body -->
            <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-body">
                    <div class="row d-flex ">
                        <div class="col-md-6 mb-3">
                            <label>نام محصول</label>
                            {{form.title}}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label>slug محصول - <button class="small-primary-button" type="button"
                                    onclick="generateSlug()">ساخت
                                    slug</button> </label>
                            {{form.slug}}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label>تعداد</label>
                            {{form.stock}}
                        </div>

                        <div class="col-md-6 mb-3">
                            <label>وضعیت</label>
                            {{form.status}}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label>دسته بندی</label>
                            {{form.category}}
                        </div>
                        <div class="col-md-4 mb-3">
                            <label>قیمت</label>
                            {{form.price}}
                        </div>
                        <div class="col-md-2 mb-3">
                            <label>درصد تخفیف</label>
                            {{form.discount_percent}}
                        </div>

                        <div class="col-md-12 mb-3">
                            <label>توضیح کوتاه</label>
                            {{form.brief_description}}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label>توضیحات</label>
                            {{form.description}}
                        </div>

                        <div class="col-md-12 mb-3">
                            <label for="validationValidFileInput1">تصویر محصول</label>
                            {{form.image}}
                        </div>


                    </div>
                    <div class="card-footer">
                        <div class=" d-flex pt-5 justify-content-end">
                            <a class="btn btn-danger ms-3"
                                href="{% url 'dashboard:admin:product-delete' pk=object.pk %}">حذف</a>
                            <a class="btn btn-secondary ms-3" href="{% url 'dashboard:admin:product-list' %}">بازگشت</a>
                            <button class="btn btn-primary ms-3" type="submit">ثبت تغییرات</button>
                        </div>
                    </div>
            </form>
        </div>
    </div>
    <div>
        <div class="card">
            <!-- Header -->
            <div class="card-header border-bottom d-flex justify-content-between align-items-center">
                <h5 class="card-header-title">ویرایش تصاویر بیشتر</h5>
            </div>
            <!-- End Header -->

            <!-- Body -->
            <form action="{% url 'dashboard:admin:product-add-image' pk=object.pk %}" method="post"
                enctype="multipart/form-data">

                {% csrf_token %}
                <div class="card-body">
                    <div class="row d-flex align-items-center">
                        <div class="col-md-9 mb-3 d-flex align-items-center">
                            <label>تصویر محصول</label>
                            {{image_form.file}}
                        </div>
                        <div class="col-md-3 mb-3">
                            <button class="btn btn-primary ms-3" type="submit">ثبت تصویر</button>
                        </div>
                    </div>
                </div>


            </form>

            <div class="card-body">
                <div class="row d-flex ">
                    {% for product_image in object.product_images.all %}
                    <div class="col-md-2">
                        <img class="img-fluid" style="width:100px; height:100px" src="{{product_image.file.url}}"
                            alt="Image Description">
                        <form action="{% url 'dashboard:admin:product-remove-image' pk=object.pk image_id=product_image.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">حذف تصویر</button>
                        </form>
                    </div>
                    {% endfor %}


                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script>

    function generateSlug() {
        const title = $("#id_title").val();
        const slug = slugify(title);
        $("#id_slug").val(slug)
    }

    function slugify(titleStr) {
        titleStr = titleStr.replace(/^\s+|\s+$/g, '');
        titleStr = titleStr.toLowerCase();
        //persian support
        titleStr = titleStr.replace(/[^a-z0-9_\s-ءاأإآؤئبتثجحخدذرزسشصضطظعغفقكلمنهويةى]#u/, '')
            // Collapse whitespace and replace by -
            .replace(/\s+/g, '-')
            // Collapse dashes
            .replace(/-+/g, '-');
        slugStr = titleStr;
        return slugStr;
    }
</script>
{% endblock %}

{% block extra_js_no_compress %}
<script src="{% static 'vendor/ckeditor/ckeditor.js' %}"></script>
<script>
    // Replace 'editor' with the id of your textarea
    CKEDITOR.replace('ckeditor');
</script>
{% endblock %}