core/cart/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cart'


urlpatterns = [
    path("session/add-product/",views.SessionAddProductView.as_view(),name="session-add-product"),
    path("session/remove-product/",views.SessionRemoveProductView.as_view(),name="session-remove-product"),
    path("session/update-product-quantity/",views.SessionUpdateProductQuantityView.as_view(),name="session-update-product-quantity"),
    path("summary/",views.CartSummaryView.as_view(),name="cart-summary")
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('review/', include('review.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),
                    ]

core/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path("validate-coupon/",views.ValidateCouponView.as_view(),name="validate-coupon"),
    path("checkout/",views.OrderCheckOutView.as_view(),name="checkout"),
    path("completed/",views.OrderCompletedView.as_view(),name="completed"),
    path("failed/",views.OrderFailedView.as_view(),name="failed"),

]

core/shop/urls.py
from django.urls import path, re_path
from . import views

app_name = 'shop'

urlpatterns = [
    path("product/grid/", views.ShopProductGridView.as_view(), name="product-grid"),
    re_path(r"product/(?P<slug>[-\w]+)/detail/",views.ShopProductDetailView.as_view(),
    name="product-detail"),
    path("add-or-remove-wishlist/", views.AddOrRemoveWishlistView.as_view(), name="add-or-remove-wishlist"),

]

core/order/forms.py
from django import forms
from order.models import UserAddressModel,CouponModel
from django.utils import timezone

class CheckOutForm(forms.Form):
    address_id = forms.IntegerField(required=True)
    coupon = forms.CharField(required=False)
    
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(CheckOutForm, self).__init__(*args, **kwargs)
        
    def clean_address_id(self):
        address_id = self.cleaned_data.get('address_id')

        # Check if the address_id belongs to the requested user
        user = self.request.user  # Assuming the user is available in the request object
        try:
            address = UserAddressModel.objects.get(id=address_id, user=user)
        except UserAddressModel.DoesNotExist:
            raise forms.ValidationError("Invalid address for the requested user.")

        return address
    
    def clean_coupon(self):
        code = self.cleaned_data.get('coupon')
        if code == "":
            return None
        # Check if the address_id belongs to the requested user
        user = self.request.user  # Assuming the user is available in the request object
        coupon = None
        try:
            coupon = CouponModel.objects.get(code=code)
        except CouponModel.DoesNotExist:
            raise forms.ValidationError("کد تخفیف اشتباه است")
        if coupon:

            if coupon.used_by.count() >= coupon.max_limit_usage:
                raise forms.ValidationError("محدودیت در تعداد استفاده")


            if coupon.expiration_date and coupon.expiration_date < timezone.now():
                raise forms.ValidationError("کد تخفیف منقضی شده است")


            if user in coupon.used_by.all():
                raise forms.ValidationError("این کد تخفیف قبلا توسط شما استفاده شده است")

        return coupon

core/dashboard/admin/views/orders.py
from django.views.generic import UpdateView,DeleteView,CreateView,ListView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from dashboard.permissions import HasAdminAccessPermission

from dashboard.admin.forms import *
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages
from django.core.exceptions import FieldError
from order.models import OrderModel,OrderStatusType

class AdminOrderListView(LoginRequiredMixin, HasAdminAccessPermission, ListView):
    template_name = "dashboard/admin/orders/order-list.html"
    paginate_by = 10
    
    def get_paginate_by(self, queryset):
        return self.request.GET.get('page_size',self.paginate_by)

    def get_queryset(self):
        queryset = OrderModel.objects.all()
        if search_q := self.request.GET.get("q"):
            queryset = queryset.filter(id__icontains=search_q)
        if status := self.request.GET.get("status"):
            queryset = queryset.filter(status=status)
        if order_by := self.request.GET.get("order_by"):
            try:
                queryset = queryset.order_by(order_by)
            except FieldError:
                pass
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total_items"] = self.get_queryset().count()  
        context["status_types"] = OrderStatusType.choices
        return context
    
class AdminOrderDetailView(LoginRequiredMixin, HasAdminAccessPermission, DetailView):
    template_name = "dashboard/admin/orders/order-detail.html"

    def get_queryset(self):
        return OrderModel.objects.all()
    
class AdminOrderInvoiceView(LoginRequiredMixin, HasAdminAccessPermission, DetailView):
    template_name = "dashboard/admin/orders/order-invoice.html"

    def get_queryset(self):
        return OrderModel.objects.filter(status=OrderStatusType.success.value)

core/dashboard/customer/views/orders.py
from django.views.generic import UpdateView,DeleteView,CreateView,ListView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from dashboard.permissions import HasCustomerAccessPermission

from dashboard.customer.forms import *
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages
from django.core.exceptions import FieldError
from order.models import OrderModel,OrderStatusType

class CustomerOrderListView(LoginRequiredMixin, HasCustomerAccessPermission, ListView):
    template_name = "dashboard/customer/orders/order-list.html"
    paginate_by = 5
    
    def get_paginate_by(self, queryset):
        return self.request.GET.get('page_size',self.paginate_by)

    def get_queryset(self):
        queryset = OrderModel.objects.filter(user=self.request.user)
        if search_q := self.request.GET.get("q"):
            queryset = queryset.filter(id__icontains=search_q)
        if status := self.request.GET.get("status"):
            queryset = queryset.filter(status=status)
        if order_by := self.request.GET.get("order_by"):
            try:
                queryset = queryset.order_by(order_by)
            except FieldError:
                pass
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total_items"] = self.get_queryset().count()
        context["status_types"] = OrderStatusType.choices  
        return context
    
class CustomerOrderDetailView(LoginRequiredMixin, HasCustomerAccessPermission, DetailView):
    template_name = "dashboard/customer/orders/order-detail.html"

    def get_queryset(self):
        return OrderModel.objects.filter(user=self.request.user)
    
class CustomerOrderInvoiceView(LoginRequiredMixin, HasCustomerAccessPermission, DetailView):
    template_name = "dashboard/customer/orders/order-invoice.html"

    def get_queryset(self):
        return OrderModel.objects.filter(user=self.request.user,status=OrderStatusType.success.value)

core/order/views.py
from django.http import HttpResponse
from django.views.generic import (
    TemplateView,
    FormView,
    View
)
from django.contrib.auth.mixins import LoginRequiredMixin
from order.permissions import HasCustomerAccessPermission
from order.models import UserAddressModel
from order.forms import CheckOutForm
from cart.models import CartModel, CartItemModel
from order.models import OrderModel, OrderItemModel
from django.urls import reverse_lazy
from cart.cart import CartSession
from decimal import Decimal
from order.models import CouponModel
from django.http import JsonResponse
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import redirect
# Create your views here.
from payment.zarinpal_client import ZarinPalSandbox
from payment.models import PaymentModel


class OrderCheckOutView(LoginRequiredMixin, HasCustomerAccessPermission, FormView):
    template_name = "order/checkout.html"
    form_class = CheckOutForm
    success_url = reverse_lazy('order:completed')

    def get_form_kwargs(self):
        kwargs = super(OrderCheckOutView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        user = self.request.user
        cleaned_data = form.cleaned_data
        address = cleaned_data['address_id']
        coupon = cleaned_data['coupon']

        cart = CartModel.objects.get(user=user)
        order = self.create_order(address)

        result = self.create_order_items(order, cart, self.request)

        # self.create_order_items(order, cart)

        # چک کردن نتیجه اگر موجودی کافی نبود
        if result:
            return result  # برگرداندن صفحه checkout با پیام خطا

        self.clear_cart(cart)

        total_price = order.calculate_total_price()
        self.apply_coupon(coupon, order, user, total_price)
        order.save()
        # return super().form_valid(form)
        return redirect(self.create_payment_url(order))

    def create_payment_url(self, order):
        zarinpal = ZarinPalSandbox()
        response = zarinpal.payment_request(order.get_price())
        payment_obj = PaymentModel.objects.create(
            authority_id=response.get("Authority"),
            amount=order.get_price(),
        )
        order.payment = payment_obj
        order.save()
        return zarinpal.generate_payment_url(response.get("Authority"))


    def create_order(self, address):
        return OrderModel.objects.create(
            user=self.request.user,
            address=address.address,
            state=address.state,
            city=address.city,
            zip_code=address.zip_code,
        )

    def create_order_items(self, order, cart, request):
        for item in cart.cart_items.all():
            product = item.product
            
            # چک کردن موجودی محصول
            if product.stock >= item.quantity:
                # ایجاد آیتم سفارش
                OrderItemModel.objects.create(
                    order=order,
                    product=product,
                    quantity=item.quantity,
                    price=product.get_price(),
                )
                
                # کم کردن موجودی محصول
                product.stock -= item.quantity
                product.save()
            else:
                # اضافه کردن پیام خطا
                messages.error(request, f"موجودی برای محصول {product.title} کافی نیست.")
                return redirect('order:checkout')  # بازگشت به صفحه checkout


    def clear_cart(self, cart):
        cart.cart_items.all().delete()
        CartSession(self.request.session).clear()

    def apply_coupon(self, coupon, order, user, total_price):
        if coupon:
            # discount_amount = round(
            #     (total_price * Decimal(coupon.discount_percent / 100)))
            # total_price -= discount_amount

            order.coupon = coupon
            coupon.used_by.add(user)
            coupon.save()

        order.total_price = total_price

    def form_invalid(self, form):
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = CartModel.objects.get(user=self.request.user)
        context["addresses"] = UserAddressModel.objects.filter(
            user=self.request.user)
        total_price = cart.calculate_total_price()
        context["total_price"] = total_price
        context["total_tax"] = round((total_price * 9)/100)
        return context


class OrderCompletedView(LoginRequiredMixin, HasCustomerAccessPermission, TemplateView):
    template_name = "order/completed.html"

    
class OrderFailedView(LoginRequiredMixin, HasCustomerAccessPermission, TemplateView):
    template_name = "order/failed.html"


class ValidateCouponView(LoginRequiredMixin, HasCustomerAccessPermission, View):

    def post(self, request, *args, **kwargs):
        code = request.POST.get("code")
        user = self.request.user

        status_code = 200
        message = "کد تخفیف با موفقیت ثبت شد"
        total_price = 0
        total_tax = 0

        try:
            coupon = CouponModel.objects.get(code=code)
        except CouponModel.DoesNotExist:
            return JsonResponse({"message": "کد تخفیف یافت نشد"}, status=404)
        else:
            if coupon.used_by.count() >= coupon.max_limit_usage:
                status_code, message = 403, "محدودیت در تعداد استفاده"

            elif coupon.expiration_date and coupon.expiration_date < timezone.now():
                status_code, message = 403, "کد تخفیف منقضی شده است"

            elif user in coupon.used_by.all():
                status_code, message = 403, "این کد تخفیف قبلا توسط شما استفاده شده است"

            else:
                cart = CartModel.objects.get(user=self.request.user)

                total_price = cart.calculate_total_price()
                total_price = round(
                    total_price - (total_price * (coupon.discount_percent/100)))
                total_tax = round((total_price * 9)/100)
        return JsonResponse({"message": message, "total_tax": total_tax, "total_price": total_price}, status=status_code)

   

core/templates/order/checkout.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Content -->
<div class="container content-space-3 content-space-lg-5">
    <div class="row">
        <div class="col-lg-8 mb-7 mb-lg-0">
            <h4 class="mb-3">انتخاب آدرس </h4>

            <!-- Form -->
            <form action="." method="post" id="checkout-form">
                {% csrf_token %}

                <hr class="my-4">

                <div class="d-grid gap-2">

                    <!-- Check -->
                    {% for address in addresses %}
                    <div class="form-check">
                        <input type="radio" class="form-check-input" name="address_id" value="{{address.id}}" required>
                        <label class="form-check-label" for="address">
                            {{address.state}},{{address.city}},{{address.address}} ,{{address.zip_code}}</label>
                    </div>
                    {% endfor %}

                    <div class="mt-3">
                        <a class="" href="#">مدیریت آدرس ها</a>
                    </div>
                </div>

                <hr class="my-4">


                <div class="row align-items-center">



                    <div class="col-sm text-center text-sm-start">
                        <a class="link" href="{% url 'cart:cart-summary' %}">
                            بازگشت به سبد خرید<i class="bi-chevron-left small me-1"></i>
                        </a>
                    </div>
                    <!-- End Col -->
                </div>
                <!-- End Row -->
            </form>
            <!-- End Form -->
        </div>
        <!-- End Col -->

        <div class="col-lg-4">
            <div class="ps-lg-4">
                <!-- Card -->
                <div class="card card-sm shadow-sm mb-4">
                    <div class="card-body">
                        <div class="border-bottom pb-4 mb-4">
                            <h3 class="card-header-title">خلاصه سفارش</h3>
                        </div>


                        <div class="input-group border-bottom pb-4 mb-3 ">
                            <input type="text" class="form-control text-center" name="coupon" placeholder="کد تخفیف"
                                aria-label="کد تخفیف" form="checkout-form" id="coupon-input">
                            <button class="btn btn-primary" type="button" onclick="validateCoupon()"> بررسی</button>
                        </div>

                        <div class="border-bottom pb-4 mb-4">
                            <div class="d-grid gap-3">

                                <!-- End Row -->

                                <dl class="row">
                                    <dt class="col-sm-6">هزینه ارسال</dt>
                                    <dd class="col-sm-12 text-sm-end mb-0">برای تهران و حومه 35000 تومان</dd>
                                    <dd class="col-sm-12 text-sm-end mb-0">برای شهرستان ها 50000 تومان</dd>
                                </dl>
                                <!-- End Row -->
                            </div>
                        </div>

                        <div class="d-grid gap-3 mb-4">
                            <dl class="row">
                                <dt class="col-sm-6">مالیات تخمینی</dt>
                                <dd class="col-sm-12 text-sm-end mb-0">
                                    9% مالیات - 
                                    <span class="formatted-price" id="total-tax"> {{total_tax}}</span>
                                </dd>

                            </dl>
                            <!-- End Row -->

                            <dl class="row">
                                <dt class="col-sm-6">جمع کل</dt>
                                <dd class="col-sm-6 text-sm-end mb-0 formatted-price" id="total-price">{{total_price}}</dd>
                            </dl>
                            <!-- End Row -->
                        </div>

                        <div class="d-grid">
                            <button class="btn btn-primary btn-lg" type="submit" form="checkout-form" >ثبت نهایی</button>
                        </div>

                    </div>
                    <!-- End Card -->
                </div>

                <!-- Media -->
                <div class="d-flex align-items-center">
                    <div class="flex-shrink-0">
                        <div class="svg-icon svg-icon-sm text-primary">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                    d="M22.1671 18.1421C22.4827 18.4577 23.0222 18.2331 23.0206 17.7868L23.0039 13.1053V5.52632C23.0039 4.13107 21.8729 3 20.4776 3H8.68815C7.2929 3 6.16183 4.13107 6.16183 5.52632V9H13C14.6568 9 16 10.3431 16 12V15.6316H19.6565L22.1671 18.1421Z"
                                    fill="#035A4B" />
                                <path opacity="0.3" fill-rule="evenodd" clip-rule="evenodd"
                                    d="M1.98508 18V13C1.98508 11.8954 2.88051 11 3.98508 11H11.9851C13.0896 11 13.9851 11.8954 13.9851 13V18C13.9851 19.1046 13.0896 20 11.9851 20H4.10081L2.85695 21.1905C2.53895 21.4949 2.01123 21.2695 2.01123 20.8293V18.3243C1.99402 18.2187 1.98508 18.1104 1.98508 18ZM5.99999 14.5C5.99999 14.2239 6.22385 14 6.49999 14H11.5C11.7761 14 12 14.2239 12 14.5C12 14.7761 11.7761 15 11.5 15H6.49999C6.22385 15 5.99999 14.7761 5.99999 14.5ZM9.49999 16C9.22385 16 8.99999 16.2239 8.99999 16.5C8.99999 16.7761 9.22385 17 9.49999 17H11.5C11.7761 17 12 16.7761 12 16.5C12 16.2239 11.7761 16 11.5 16H9.49999Z"
                                    fill="#035A4B" />
                            </svg>

                        </div>
                    </div>
                    <div class="flex-grow-1 ms-2">
                        <span class="small me-1">نیاز به پشتیبانی دارید؟</span>
                        <a class="link small" href="#">ارسال تیکت</a>
                    </div>
                </div>
                <!-- End Media -->
            </div>
        </div>
        <!-- End Col -->
    </div>
    <!-- End Row -->
</div>
<!-- End Content -->
{% endblock content %}

{% block extra_js %}
<script>
    function applyDiscount(total_price,total_tax){
        $("#total-price").html(total_price)
        $("#total-tax").html(total_tax)

        formatPriceInToman(document.getElementById("total-price"))
        formatPriceInToman(document.getElementById("total-tax"))
    }

    function validateCoupon(){
        $.ajax({
            url: "{% url 'order:validate-coupon' %}",
            method: 'POST',
            data: {
                code: $('#coupon-input').val(),
                csrfmiddlewaretoken: '{{ csrf_token }}'
    
            },
            success: function (response) {
                console.log("success",response);
                Toastify({
                    text:response.message,
                    className: `info`,
                    style: {
                      background: "blue",
                    }
                  }).showToast();
                  applyDiscount(response.total_price,response.total_tax)
                // do something with the response data
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log(errorThrown);
                Toastify({
                    text:jqXHR.responseJSON.message,
                    className: `error`,
                    style: {
                      background: "red",
                    }
                  }).showToast();
                
                // handle the error case
            }
        });
    }

</script>

{% endblock %}

core/templates/order/completed.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Content -->
<div class="container content-space-3 content-space-lg-5">
    <div class="w-md-75 w-lg-50 text-center mx-md-auto">
        <div class="mb-5">
            <img class="img-fluid" src="{% static '/svg/illustrations/oc-hi-five.svg' %}" alt="Image Description"
                style="width: 15rem;">
        </div>

        <div class="mb-5">
            <h1 class="h2">سفارش شما تکمیل شد!</h1>
            <p>از سفارش شما متشکریم! سفارش شما در حال پردازش است و ظرف 3 تا 6 ساعت تکمیل خواهد شد. پس از تکمیل سفارش شما
                یک ایمیل تاییدیه دریافت خواهید کرد.</p>
        </div>

        <a class="btn btn-primary btn-transition rounded-pill px-6" href="{% url 'shop:product-grid' %}">به خرید ادامه دهید</a>
    </div>
</div>
<!-- End Content -->

<!-- Subscribe -->
<div class="bg-light">
    <div class="container content-space-2">
        <div class="w-md-75 w-lg-50 text-center mx-md-auto">
            <div class="row justify-content-lg-between">
                <!-- Heading -->
                <div class="mb-5">
                    <span class="text-cap">ثبت نام</span>
                    <h2>اخبار جدید را دریافت کنید</h2>
                </div>
                <!-- End Heading -->

                <form method="post" action="#">
                    {% csrf_token %}
                    <!-- Input Card -->
                    <div class="input-card input-card-pill input-card-sm border mb-3">
                        <div class="input-card-form">
                            <input class="form-control border-0 me-1" type="text" placeholder="نام"
                                        name="first_name" hidden="">
                            <label for="subscribeForm" class="form-label visually-hidden">ایمیل را وارد کنید</label>
                            <input type="email" class="form-control form-control-lg" name="email"
                                placeholder="ایمیل خود را وارد نمایید" aria-label="ایمیل خود را وارد کنید">
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg rounded-pill">ثبت نام</button>
                    </div>
                    <!-- End Input Card -->
                </form>

                <p class="small">می توانید در هر زمانی اشتراک خود را لغو کنید <a href="#">سیاست حفظ حریم خصوصی</a> ما را
                    بخوانید</p>
            </div>
        </div>
    </div>
</div>
<!-- End Subscribe -->

<!-- Clients -->
<div class="container content-space-2">
    <div class="row">
        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="/assets/svg/brands/hollister-dark.svg" alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="'/assets/svg/brands/levis-dark.svg" alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="/assets/svg/brands/new-balance-dark.svg" alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="/assets/svg/brands/puma-dark.svg" alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="/assets/svg/brands/nike-dark.svg" alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="/assets/svg/brands/tnf-dark.svg'" alt="Logo">
        </div>
        <!-- End Col -->
    </div>
    <!-- End Row -->
</div>
<!-- End Clients -->

{% endblock content %}

core/templates/order/failed.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Content -->
<div class="container content-space-3 content-space-lg-5">
    <div class="w-md-75 w-lg-50 text-center mx-md-auto">
        <div class="mb-5">
            <img class="img-fluid" src="{% static '/svg/illustrations/oc-error.svg' %}" alt="Image Description"
                style="width: 15rem;">
        </div>

        <div class="mb-5">
            <h1 class="h2">سفارش شما با شکست مواجه شد!</h1>
            
        </div>

        <a class="btn btn-primary btn-transition rounded-pill px-6" href="{% url 'shop:product-grid' %}">به خرید ادامه دهید</a>
    </div>
</div>
<!-- End Content -->

<!-- Subscribe -->
<div class="bg-light">
    <div class="container content-space-2">
        <div class="w-md-75 w-lg-50 text-center mx-md-auto">
            <div class="row justify-content-lg-between">
                <!-- Heading -->
                <div class="mb-5">
                    <span class="text-cap">ثبت نام</span>
                    <h2>اخبار جدید را دریافت کنید</h2>
                </div>
                <!-- End Heading -->

                <form method="post" action="#">
                    {% csrf_token %}
                    <!-- Input Card -->
                    <div class="input-card input-card-pill input-card-sm border mb-3">
                        <div class="input-card-form">
                            <input class="form-control border-0 me-1" type="text" placeholder="نام"
                                        name="first_name" hidden="">
                            <label for="subscribeForm" class="form-label visually-hidden">ایمیل را وارد کنید</label>
                            <input type="email" class="form-control form-control-lg" name="email"
                                placeholder="ایمیل خود را وارد نمایید" aria-label="ایمیل خود را وارد کنید">
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg rounded-pill">ثبت نام</button>
                    </div>
                    <!-- End Input Card -->
                </form>

                <p class="small">می توانید در هر زمانی اشتراک خود را لغو کنید <a href="#">سیاست حفظ حریم خصوصی</a> ما را
                    بخوانید</p>
            </div>
        </div>
    </div>
</div>
<!-- End Subscribe -->

<!-- Clients -->
<div class="container content-space-2">
    <div class="row">
        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="/assets/svg/brands/hollister-dark.svg" alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="/assets/svg/brands/levis-dark.svg" alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="/assets/svg/brands/new-balance-dark.svg" alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="/assets/svg/brands/puma-dark.svg" alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="/assets/svg/brands/nike-dark.svg" alt="Logo">
        </div>
        <!-- End Col -->

        <div class="col text-center py-3">
            <img class="avatar avatar-lg avatar-4x3" src="/assets/svg/brands/tnf-dark.svg" alt="Logo">
        </div>
        <!-- End Col -->
    </div>
    <!-- End Row -->
</div>
<!-- End Clients -->

{% endblock content %}